types = ['Drama', 'Crime', 'Action', 'Fantasy', 'Western', 'Comedy-Drama', 'Science Fiction', 'Mystery', 'Thriller', 'Animation', 'War']


top_50_movies = [    ["The Shawshank Redemption", "Frank Darabont", "Drama", 9.2, 142],
    ["The Godfather", "Francis Ford Coppola", "Crime", 9.2, 175],
    ["The Godfather: Part II", "Francis Ford Coppola", "Crime", 9.0, 202],
    ["The Dark Knight", "Christopher Nolan", "Action", 9.0, 152],
    ["12 Angry Men", "Sidney Lumet", "Drama", 8.9, 96],
    ["Schindler's List", "Steven Spielberg", "Drama", 8.9, 195],
    ["The Lord of the Rings: The Return of the King", "Peter Jackson", "Fantasy", 8.9, 201],
    ["Pulp Fiction", "Quentin Tarantino", "Crime", 8.9, 154],
    ["The Good, the Bad and the Ugly", "Sergio Leone", "Western", 8.8, 161],
    ["Fight Club", "David Fincher", "Drama", 8.8, 139],
    ["Forrest Gump", "Robert Zemeckis", "Comedy-Drama", 8.8, 142],
    ["Inception", "Christopher Nolan", "Action", 8.8, 148],
    ["The Lord of the Rings: The Fellowship of the Ring", "Peter Jackson", "Fantasy", 8.8, 178],
    ["Star Wars: Episode V - The Empire Strikes Back", "Irvin Kershner", "Science Fiction", 8.7, 124],
    ["The Lord of the Rings: The Two Towers", "Peter Jackson", "Fantasy", 8.7, 179],
    ["The Matrix", "The Wachowski Brothers", "Science Fiction", 8.7, 136],
    ["Goodfellas", "Martin Scorsese", "Crime", 8.7, 146],
    ["Se7en", "David Fincher", "Mystery", 8.6, 127],
    ["City of God", "Fernando Meirelles", "Crime", 8.6, 130],
    ["The Silence of the Lambs", "Jonathan Demme", "Thriller", 8.6, 118],
    ["It's a Wonderful Life", "Frank Capra", "Drama", 8.6, 130],
    ["Life is Beautiful", "Roberto Benigni", "Comedy-Drama", 8.6, 116],
    ["The Usual Suspects", "Bryan Singer", "Crime", 8.6, 106],
    ["Léon: The Professional", "Luc Besson", "Action", 8.5, 110],
    ["Spirited Away", "Hayao Miyazaki", "Animation", 8.5, 125],
    ["Saving Private Ryan", "Steven Spielberg", "War", 8.5, 169],
    ["Interstellar", "Christopher Nolan", "Science Fiction", 8.5, 169],
    ["American History X", "Tony Kaye", "Drama", 8.5, 119],
    ["The Green Mile", "Frank Darabont", "Fantasy", 8.5, 189],
    ["The Prestige", "Christopher Nolan", "Mystery", 8.5, 130],
    ]
